name: tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop
      - main

jobs:
  code_base_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Aspell
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y aspell aspell-en

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Setup Meilisearch
        run: |
          # Install Meilisearch
          curl -L https://github.com/meilisearch/Meilisearch/releases/download/v1.14.0/meilisearch-linux-amd64.tar.gz | tar xz
          mv meilisearch /usr/local/bin
          # Start Meilisearch in the background
          nohup meilisearch --env production --http-addr '0.0.0.0:7700' &

      - name: Set Meilisearch Environment Variables
        run: |
          echo "MEILISEARCH_HOST=http://localhost:7700" >> .env
          echo "MEILISEARCH_API_KEY=your_meilisearch_api_key" >> .env

      - name: Tests
        run: composer test

      - name: Format Frontend
        run: npm run format

      - name: Lint Frontend
        run: npm run lint

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: format frontend"
          commit_options: '--no-verify'